-- GAP-19: Server-side sequence for disbursement memo numbers (race-condition safe)
CREATE SEQUENCE IF NOT EXISTS disbursement_memo_seq START 1;

CREATE OR REPLACE FUNCTION generate_memo_number()
RETURNS TRIGGER AS $$
BEGIN
  NEW.memo_number := 'DM-' || TO_CHAR(CURRENT_DATE, 'YYYYMMDD') || '-' || LPAD(nextval('disbursement_memo_seq')::TEXT, 4, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_memo_number ON disbursement_memos;
CREATE TRIGGER set_memo_number
  BEFORE INSERT ON disbursement_memos
  FOR EACH ROW
  WHEN (NEW.memo_number IS NULL OR NEW.memo_number = '')
  EXECUTE FUNCTION generate_memo_number();

-- GAP-18: Add currency check constraint for disbursement_memos vs invoices
-- This is enforced at application level (see Disbursements.tsx) but also add a check for the column
-- We add comment as documentation of the rule
COMMENT ON TABLE disbursement_memos IS 'memo_number is generated by trigger. Currency must match the invoice currency (enforced by application).';

-- Add pending_offer_review to funder marketplace visibility checks
-- (No schema change needed, enforced in application filtering)
